/*
@name Error tracing
@category Try
This test creates a bit of traceback. It can be 
checked by hand to see if the traceback is correct
in terms of desired output and source lines.

The automated test checks if the traceback has
been properly generated only when requestsed.

@result Ok
*/

class test
   function third()
      // generate an error
      a = nil + 1
   end
end

function first( count )
   if count < 3
      first( count + 1)
   end

   second( 0 )
end

function second( count )
   if count < 2
      second( count + 1 )
   end
   t = test()
   t.third( count + 1 )
end


try
   first(0)
catch in e
   > "Untraced error:"
   > e
   trace0 = e.trace
end

>

try
   first(0)
catch as e
   > "Traced error:"
   > e
   trace1 = e.trace
end

if trace0 == nil and trace1.len >= 9 and trace1.len <= 10
   >
   > "Success"
   return "Ok"
end

> "... Fail incoming"
return "Fail"
